---
abstract: 'Session Manager for the Yakuake Terminal Emulator'
author:
  - 'Peter Flanigan, C<< <pjfl@cpan.org> >>'
build_requires:
  Module::Build: 0.4004
  version: 0.88
configure_requires:
  Module::Build: 0.4004
  version: 0.88
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Yakuake-Sessions
no_index:
  directory:
    - bin
    - examples
    - inc
    - share
    - t
provides:
  Yakuake::Sessions:
    file: lib/Yakuake/Sessions.pm
    version: v0.7.4
  Yakuake::Sessions::Base:
    file: lib/Yakuake/Sessions/Base.pm
    version: v0.7.1
  Yakuake::Sessions::Config:
    file: lib/Yakuake/Sessions/Config.pm
    version: v0.7.1
  Yakuake::Sessions::TraitFor::DBus:
    file: lib/Yakuake/Sessions/TraitFor/DBus.pm
    version: v0.7.2
  Yakuake::Sessions::TraitFor::FileData:
    file: lib/Yakuake/Sessions/TraitFor/FileData.pm
    version: v0.7.2
  Yakuake::Sessions::TraitFor::Management:
    file: lib/Yakuake/Sessions/TraitFor/Management.pm
    version: v0.7.1
  Yakuake::Sessions::TraitFor::TabTitles:
    file: lib/Yakuake/Sessions/TraitFor/TabTitles.pm
    version: v0.7.1
recommends:
  App::cpanminus: 1.6005
requires:
  Class::Usul: v0.22.0
  File::DataClass: v0.22.0
  Moo: 1.002
  MooX::Options: 3.83
  Net::DBus: v1.0.0
  namespace::sweep: 0.006
  perl: 5.01
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Yakuake-Sessions
  homepage: http://www.roxsoft.co.uk
  license: http://dev.perl.org/licenses/
  repository: git://github.com/pjfl/Yakuake-Sessions.git
version: v0.7.4
